apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.33.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--rule.files=/etc/prometheus/alerts.yml"
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-alert-rules
              mountPath: /etc/prometheus/alerts.yml
              subPath: alerts.yml
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-alert-rules
          configMap:
            name: prometheus-alert-rules
